### ISSUE TITLE
Integrate see.rt.Class

### ISSUE THREAD

**Issue by Yevano** [Yevano/see#23]
Runtime classes should be represented by instances of `see.rt.Class`.

**Comment by ghost** [comment]
uhm

**Comment by Yevano** [comment]
Pretty much impossible due to metatable loopback and indexing ambiguities.

**Comment by Yevano** [comment]
Reopening this because it _might_ be possible by checking the table given to the `__index` method to see if it is a class.

**Comment by Yevano** [comment]
After some tests, the task seems doable using special cases for classes in metamethods. I'll make a new branch for the new classes once I'm ready to start adding the feature to the SEE runtime.

**Comment by Yevano** [comment]
Note to self: Write implementation for `Object:super(class).method(...)`.

Something like:

``` lua
function Object:super(class)
    local obj = self
    return setmetatable({ }, { __index = function(t, k)
        return function(...)
            return rawget(class, "__table")[k](obj, ...)
        end
    end })
end
```

**Comment by Yevano** [comment]
better-classes branch is nearly ready to be merged

**Comment by Yevano** [comment]
Merged
